language: cpp
compiler:
- g++
env:
- CXX=g++-7
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-7', 'ninja-build']
os:
- linux
install:
- sudo pip install codecov
script:
- export CXX="g++-7"
- export LCOV_FLAGS="--gcov-tool /usr/bin/gcov-7"
# Build lcov
- git clone https://github.com/linux-test-project/lcov
- cd lcov
- sudo make install
- cd ..
- make -j2 test_run
branches:
  only:
  - develop
after_success:
- codecov -t ed9d8a5e-97f3-43c3-9cf2-ec4bc648f588 -X gcov -f final.info

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: html
  on:
    branch: develop
